### ISSUE TITLE
Total heat displayed at the bottom of the window is incorrect for one-shot missiles/torpedoes, Streaks, and rocket launchers

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#748] opened 2020-08-11 04:19 UTC
Using MML 0.47.9, the Heat display at the bottom of the window counts one-shot (and improved one-shot) missile systems as having one quarter of their normal heat. It also counts streak missile systems and rocket launchers as having half of their normal heat (or one quarter for one-shot streaks). This applies to all kinds of missiles and torpedoes. Heat values are displayed correctly in the Equipment Database and Current Loadout panels under the Equipment tab.

Regular LRM/SRM/MRM/LRT/SRT launchers, Mech mortars, ATMs, and Thunderbolt missiles appear to be normal.

Example:
1) Start a new 'Mech. The total heat value displayed at the bottom of the window is 2, which is correct.
2) Add a one-shot SRM 2 system. Its listed heat is 2, which is correct, but the heat value displayed at the bottom of the window is 2.5 instead of the correct value of 4. The total heat increased by 0.5 instead of 2.
3) Add an improved one-shot LRT 10 system. Its listed heat value is 4, which is correct, but the heat value displayed at the bottom is 3.5 instead of the correct value of 8. The total heat increased by 1 instead of 4.
4) Add a one-shot Streak SRM 2 system. Its listed heat is 2, which is correct, but the heat value displayed at the bottom is 3.75 instead of the correct value of 10. The total heat increased by 0.25 instead of 2.
Add a one-shot MRM 40. Its listed heat is 12, which is correct, but the heat value displayed at the bottom is 6.75 instead of the correct value of 22. The total heat increased by 3 instead of 12.
5) Add a regular Streak SRM 6. Its listed heat is 4, which is correct, but the heat value displayed at the bottom is 8.75 instead of the correct value of 26. The total heat increased by 2 instead of 4.
6) Add a RL 20. Its listed heat is 5, which is correct, but the heat value displayed at the bottom is 10 instead of the correct value of 31. The total heat increased by 1.25 instead of 5.

**Comment by neoancient** [comment] 2020-08-11 13:34
Duplicate of #268

**Closed by neoancient** 2020-08-11 13:34 UTC
Labels: duplicate
