### ISSUE TITLE
Battle Armor modular weapon mounts are missing from the editor entirely

### ISSUE THREAD

**Issue by Lincolnator42069** [MegaMek/megameklab#1522] opened 2024-06-11 23:55 UTC
I have already searched for any open or closed issues on this, and I have not found any

### Environment
 I am using stand alone MekLab version 0.49.19.1 on windows 10, with java version 22.

The issue is quite simple, there seems to be no option for modular standard equipment mounts on battle armor.  On TM, pp. 262, you can place a standard modular weapon mount in much the same way as an AP modular weapon mount, but it weighs 10kg instead of 5 kg, and takes up a crit space.  I can find no such equipment in the equipment editor, and there is no menu option when right clicking the equipment in the assign criticals menu like there is with squad weapon mounts.  

I have restarted the program several times and made several different categories of battle armor, and it does not appear, which makes me think that this is simply something that hasn't been implemented yet.  

It should be a simple thing to add, just add an equipment that is a 10kg version of the AP weapon mount and have it do nothing, it serves as a placeholder saying that this has a modular weapons adapter present.  

Until this gets fixed I am simply going to use the AP modular weapons mount and make sure the suits are 5kg under weight.

[megameklab.log](https://github.com/user-attachments/files/15795819/megameklab.log)

**Comment by gsparks3** [comment] 2024-06-12 00:39
Duplicate of #911 (although it really has been quite a while for it to hang around unimplemented)

**Closed by gsparks3** 2024-06-12 00:39 UTC
Labels: duplicate
