### ISSUE TITLE
Superheavy mechs causes error on Tech Base

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megameklab#669] opened 2020-07-07 19:59 UTC
### Environment
Ver 0.47.7
Windows 10

### Description
If you load any random superheavy mech, or reset and raise the Tonnage of New Mek over than 100, Tech Base is set to _-error-_ and there is no way to change it, unless revert it to non-superheavy.

Ver 0.47.6 doesn't have the same error; only 0.47.7 does.

**Comment by neoancient** [comment] 2020-07-07 20:59
Duplicate of #657

**Closed by neoancient** 2020-07-07 20:59 UTC
Labels: duplicate
