### ISSUE TITLE
Changing mix tech base and then mek weight resets other fields

### ISSUE THREAD

**Issue by foij00** [MegaMek/megameklab#245] opened 2019-01-26 02:31 UTC
Meklab version 0.45.2.
Windows 10
Java version 8 Update 201 (build 1.8.0_201-b09)

reset current unit (new mek)
select tech base as mixed inner sphere or mixed clan
then change tonnage
tech base resets to inner sphere, tech level to advanced, and year to 2460.
other weirdness happens, like cockpit goes to -error-
run mp gets locked to 2, no matter walk mp.
jump mp cannot go higher than 1.

I can only reproduce this error from a fresh program start or after reset current unit.

![clipboard01](https://user-images.githubusercontent.com/45526752/51781581-19da2280-20e0-11e9-97ef-0d3d1076af8a.jpg)

**Comment by foij00** [comment] 2019-01-26 02:40
Changing tech base or tech level mid-way through editing a mek also appears to trigger similar issues.

**Comment by neoancient** [comment] 2019-01-26 03:03
Duplicate of #242

**Closed by neoancient** 2019-01-26 03:03 UTC
Labels: duplicate
