### ISSUE TITLE
0.47.2 - Space Station - Other Equipment Shows Weapons and Equipment

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/megameklab#407] opened 2020-01-26 14:04 UTC
![image](https://user-images.githubusercontent.com/39067288/73136360-d1b74e00-401a-11ea-8c64-e6def07b4165.png)

**Comment by neoancient** [comment] 2020-01-26 14:11
Duplicate of #390

**Closed by neoancient** 2020-01-26 14:11 UTC
Labels: duplicate
