### ISSUE TITLE
MML 0.47.5 LAMs fail to load

### ISSUE THREAD

**Issue by LiamsGhost** [MegaMek/megameklab#597] opened 2020-04-25 01:49 UTC
Attempting to load a previously created LAM results in a failure to load. No warnings are given, nor is there anything in the log file. The majority of designs I attempted to load were valid, correct, and loaded without error in MML 0.46.1, though this error also occurred with an LAM previously created in 0.47.5.

**Comment by neoancient** [comment] 2020-04-25 12:43
Duplicate of #553

**Closed by neoancient** 2020-04-25 12:43 UTC
Labels: duplicate
