### ISSUE TITLE
BV Calculation showing in C-Bill cost under Validation Menu

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#590] opened 2020-04-23 15:09 UTC
As the title.

When you load an infantry unit and use Unit Validation-Unit Cost Breakdown it's showing the BV breakdown rather than the c-bill cost break down.

Also Impacts:
- Conv/Aero
- BattleArmor screen shows Blank
- ProtoMek
- Prim-Aero

### Environment
What version of MekLab does your issue apply to?  47.5
What operating system are you using?  Windows,

**Comment by neoancient** [comment] 2020-04-23 15:19
Duplicate of #494

**Closed by neoancient** 2020-04-23 15:19 UTC
Labels: duplicate
