### ISSUE TITLE
(0.45.2) BA Detachable Weapon Mount prevents saving

### ISSUE THREAD

**Issue by Xeno426** [MegaMek/megameklab#244] opened 2019-01-11 16:45 UTC
### Environment
0.45.2
Platform Windows 7 6.1 (x86)
Java version 1.8.0_151

### Description
When creating a BA, Detachable Weapon Mounts prevent saving if anything is placed in them.
After several attempts, I've found that putting anything inside of the DWP keeps MML from actually saving the file. Simply having DWP on the unit doesn't cause any issues; a weapon has to be placed inside the DWP.
Choosing "Save As" will bring up the save dialog, but the confirmation message about the file being saved does not pop up and the unit file does not appear.

**Comment by neoancient** [comment] 2019-01-11 18:23
Duplicate of #231

**Closed by neoancient** 2019-01-11 18:23 UTC
Labels: duplicate
