### ISSUE TITLE
Fluff image printed in light blue

### ISSUE THREAD

**Issue by offbyoni** [MegaMek/megameklab#1266] opened 2023-05-29 13:19 UTC
### Environment
MegaMek (MekHQ) 0.49.11
Mac OS X Ventura 13.3.1(a)
openjdk 20 2023-03-21

### Description
When printing a record sheet, the fluff image is printed in light blue (see first screenshot, from .ps output). The era image is also printed almost invisibly and weirdly (see second screenshot).

### Files
<img width="623" alt="image" src="https://github.com/MegaMek/megameklab/assets/15029854/c6cb432f-0805-46ea-994c-3b133b6173f5">
<img width="685" alt="image" src="https://github.com/MegaMek/megameklab/assets/15029854/000b044c-b088-488e-82e2-9351f53e3afa">

[megameklab.log](https://github.com/MegaMek/megameklab/files/11592036/megameklab.log)

**Comment by SJuliez** [comment] 2023-06-08 09:32
I can't reproduce this with the 49.11 versions of MML. Can you try again and remove or rename the fluff image, so it isn't printed? Also, the RS has other issues that I can't see in 49.11, such as misplaced text and lines. Is this really from a clean install of MHQ/MML?

**Comment by HammerGS** [comment] 2023-06-09 16:52
Are you using "Print to" options?  If so try with Export to PDF. We've had reports over the years of weirdness printing and with all the Java to printer driver to OS interactions it's impossible to trouble shoot or fix.

We find using export to PDF seems to be the most stable and consistent way of printing RS.

**Comment by UrsKR** [comment] 2023-06-13 17:19
@HammerGS , if that is the case, why not drop print support and stick to PDF?

**Comment by SJuliez** [comment] 2023-07-08 08:19
Many people can print just fine and if one path doesn't work for someone they have an alternative to try. Closing this as we probably won't be able to do anything about it.

**Closed by SJuliez** 2023-07-08 08:19 UTC
Labels: Can't reproduce
