### ISSUE TITLE
ArrayIndexOutOfBoundsException when previewing 'Mechs with hardened armor

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#573] opened 2020-04-11 22:43 UTC
Using MML 0.47.5 on OS X with Java build 1.8.0_51-b16, I get ArrayIndexOutOfBoundsExceptions when I preview or load a 'Mech with hardened armor. Vehicles with hardened armor work fine. I have attached the log file.
[megameklablog.txt](https://github.com/MegaMek/megameklab/files/4465585/megameklablog.txt)

**Comment by neoancient** [comment] 2020-04-16 17:06
Duplicate of MegaMek/megamek#1853. Closing this one, as the other one has more information and is on the tracker relevant to the issue.

**Closed by neoancient** 2020-04-16 17:06 UTC
Labels: duplicate
