### ISSUE TITLE
Infantry unit weight and cost breakdowns do not work

### ISSUE THREAD

**Issue by twhws** [MegaMek/megameklab#829] opened 2020-11-14 16:29 UTC
### Environment
Meklab 0.47.11, Windows 8.1, Java 11.0.5

### Description
1. In the dropdown "Unit Validation"->"Unit Cost Breakdown" -> "Breakdown Current Unit" shows a new window with "Battle Value Calculations For New Infantry" instead of cost breakdown. No new entries in megameklog.txt when doing that.

2. Dropdown "Unit Validation"->"Unit Weight Breakdown"->"Breakdown Current Unit" just doesn't work at all, no new windows, but add a NullPointerException in megameklab.com.util.UnitUtil.showUnitWeightBreakDown(UnitUtil.java:3860) trace
to the megameklog.txt 

[megameklablog.txt](https://github.com/MegaMek/megameklab/files/5541089/megameklablog.txt)

**Comment by neoancient** [comment] 2020-11-14 16:42
Duplicate of #494

**Closed by neoancient** 2020-11-14 16:42 UTC
Labels: duplicate
