### ISSUE TITLE
Unable to export PDF - SVG class reference

### ISSUE THREAD

**Issue by creature-ish** [MegaMek/megameklab#1284] opened 2023-07-13 03:05 UTC
### Environment
MegaMekLab (Bundled with MekHQ) version 0.49.13
Windows 10 version 10.0
Adoptium Java version 11.0.19

### Description
MegaMekLab throws an alert with ``java.lang.NoClassDefFoundError:org/w3c/svg/SVGDocument`` upon selecting ``File > Export > PDF > Current Unit`` and assigning an output filename. Reproduced when trying to export included 'Mechs and custom 'Mechs with and without fluff images, can also be reproduced by attempting to print using Microsoft Print to PDF.

### Files
[megameklab.log](https://github.com/MegaMek/megameklab/files/12034942/megameklab.log)

**Comment by HammerGS** [comment] 2023-07-13 03:09
Duplicate of https://github.com/MegaMek/megameklab/issues/1263

you need to use 49.12 and should be fixed for 49.14

**Closed by HammerGS** 2023-07-13 03:09 UTC
