### ISSUE TITLE
Feature Request: Change Unit Icon

### ISSUE THREAD

**Issue by MaxSizeis** [MegaMek/megameklab#335] opened 2019-08-11 21:02 UTC
A setting or window to easily change the Megamek icon for a unit when customizing it in MegamekLab. I know there must be some way to set the icon for a unit manually, but including a setting in the program itself would be handy.

**Comment by neoancient** [comment] 2019-08-22 13:53
Duplicate of #27

**Closed by neoancient** 2019-08-22 13:53 UTC
Labels: duplicate
