### ISSUE TITLE
RFE: Split Total Heat Generated into Multiple Columns

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/megameklab#569] opened 2020-04-10 22:22 UTC
This is a request to split the heat display into either three or four categories: motionless/ { either heat from running or split between walking or running} / Jumping.

I think this display format would be very useful for designing BattleMechs, and probably others too.

**Comment by neoancient** [comment] 2020-07-21 15:10
Essentially a duplicate of #569

**Comment by Windchild292** [comment] 2020-07-21 15:11
It is a duplicate of itself?

**Closed by neoancient** 2020-07-21 15:10 UTC
Labels: Good First Issue, duplicate, enhancement
