### ISSUE TITLE
[0.49.15] Auto-fill criticals (endo-steel, etc.) behavior leads to exception error when adding XL engine to Partial Wing mek

### ISSUE THREAD

**Issue by TimberWolfD** [MegaMek/megameklab#1336] opened 2023-11-16 22:40 UTC
### Environment
Environment
MML 49.14 (usingMegaMekLab.exe)
Windows 10
Adoptium jdk 17.0.8 (Java 19.0.1 per megameklab.log)

### Description
Adding XL/XXL engines to a Mek with partial wing and full torso criticals (with movable items like endo-steel) causes an error that can trigger an exception warning.

Steps to replicate:
1. Add crit filling equipment (I usually encounter this with endo-steel, an armor, and TSM filling many crits)
![MegaMekLab crit displacement crash setup](https://github.com/MegaMek/megameklab/assets/143316586/d4b71b24-df51-4f2c-8bd5-bcbb969663ad)
2. Try to add partial wing (Which I have had crash at this step)
![MegaMekLab crit displacement crash setup Partial Wing](https://github.com/MegaMek/megameklab/assets/143316586/0af8421e-62b7-4acd-b1e7-917d759b4db8)
2B. Accept warning and manually rearrange criticals to add partial wing successfully.
3. Change engine type to XL/XXL
![MegaMekLab crit displacement crash](https://github.com/MegaMek/megameklab/assets/143316586/c9ff3093-2a87-47c9-84f8-042d1f5674e7)

### Files
[megameklab.log](https://github.com/MegaMek/megameklab/files/13384706/megameklab.log)

**Comment by neoancient** [comment] 2024-04-04 19:53
Duplicate of #1171, fixed by 1405

**Closed by neoancient** 2024-04-04 19:53 UTC
Labels: Bug, Mek
