### ISSUE TITLE
[0.49.18] Opening equipment tab for aerospace/conventional fighters causes NPE

### ISSUE THREAD

**Issue by sirbayer** [MegaMek/megameklab#1438] opened 2024-02-22 23:04 UTC
### Environment
HQ MekLab 0.49.18
Windows 10
Java 17.0.10

### Description
Opening the equipment tab on the aerospace/conventional fighter screen causes an NPE, a failure to refresh the window's graphics, and (it appears) no equipment loading. The Criticals screen still loads correctly and displays all installed equipment.

Happens in all circumstances - selecting 'new Aerospace' from the startup menu, swapping to it from the File -> Switch Unit Type menu, or loading an extant aerospace file.

Also appears to reset the armor tonnage on support fixed-wing craft.

### Files
[megameklab.log](https://github.com/MegaMek/megameklab/files/14380191/megameklab.log)

**Comment by Sleet01** [comment] 2024-02-22 23:15
The NPE is a duplicate of MegaMek/megamek#5176

I believe the armor tonnage issue has also been fixed so I'll close this for now, but I'll double-check that and re-open if not.

**Closed by Sleet01** 2024-02-22 23:15 UTC
