### ISSUE TITLE
[49.11] Cannot select "Standard Cockpit" on Industrialmech to apply Advanced Fire Control

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megameklab#1237] opened 2023-02-12 19:16 UTC
In previous versions of MML, the Advanced Fire Control modification was applied to Industrialmechs by selecting the "Standard Cockpit" option from the dropdown menu (see below, taken in 0.48).
![image](https://user-images.githubusercontent.com/59574316/218332008-9ce9a67a-8493-4e88-99d3-0570c299c4a1.png)
As of 0.49.11, this option is no longer available at any tech level, preventing Industrialmechs from being given Advanced Fire Control without direct unit file editing.
![image](https://user-images.githubusercontent.com/59574316/218332057-eb12da8d-9933-4b08-aa71-fe78a652852a.png)
![image](https://user-images.githubusercontent.com/59574316/218332067-da23d5ac-0344-412c-b4bc-0b1724addafa.png)
This option should be restored.

**Comment by foij00** [comment] 2023-04-30 04:31
Can confirm, and the Inquisitor II ITW-200 requires an advanced FCS because it mounts a Beagle Active Probe.

**Comment by HammerGS** [comment] 2023-04-30 15:30
This adding Advanced Fire Control as of 49.12

![image](https://user-images.githubusercontent.com/13752452/235361614-40663c19-797f-4edc-96ab-14cbdac8a5c0.png)

![image](https://user-images.githubusercontent.com/13752452/235361639-61856839-5efe-479b-af81-eeae8c659779.png)

This issue is you can't NOT add advanced control. Realistically we need a check box to add it.

**Comment by gsparks3** [comment] 2023-04-30 15:38
Ah, I see. Yeah, you seem to be correct - it automatically adds the advanced fire control option, and there seems to be no way to remove it. Dropdown option in cockpit selector, right-click option on the assign criticals menu, or a checkbox would all work. 

Displaying it like this is definitely better than previously, though - it was a little unintuitive to call it a "standard cockpit" versus "industrial cockpit with advanced fire control".

**Comment by neoancient** [comment] 2024-02-08 04:39
Duplicate of #1330

**Closed by neoancient** 2024-02-08 04:39 UTC
Labels: Bug, Mek
