### ISSUE TITLE
Aft Left and Aft are swapped in the UI for weapons bays on Spherical Dropships

### ISSUE THREAD

**Issue by BlueThing00** [MegaMek/megameklab#236] opened 2018-12-19 20:37 UTC
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
MML 0.45.2
Windows 10
Java 10

### Description
I'm trying to customize a spherical dropship.  When I remove the weapons and add new ones, the weapon bay I added to the Aft Left location in the UI appears to be treated as Aft everywhere else (in the Preview and when checking for balanced weapons for Validation).

Steps to reproduce:
1) Load up a Spherical Dropship such as the Mule
2) Remove all equipment
3) Add two identical weapons
4) Place them in Aft Left and Aft Right
5) Validate indicates the weapons are not balanced and Preview shows the Aft Left weapon as Aft

### Files
n/a

**Comment by neoancient** [comment] 2018-12-19 21:38
Duplicate of #234

**Closed by neoancient** 2018-12-19 21:38 UTC
Labels: duplicate

**Comment by BlueThing00** [comment] 2018-12-19 23:21
It may be more complex than that.  When two bays per location, with exactly the same weapons on all six locations, the ship does not validate.  I'm not sure exactly what is happening.
