### ISSUE TITLE
Marian Hegemony armor kit is listed as divisor 2.0 but previews and prints as 1.0

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megameklab#1243] opened 2023-04-08 20:18 UTC
When building advanced infantry in 49.12, the damage divisor for Marian Hegemony Kit is listed at 2.0 but the preview and print output shows as 1.0:

![Marian Hegemony armor kit](https://user-images.githubusercontent.com/70451747/230740918-1355a075-eefa-45b4-98ee-51a851af24e5.png)

One of these values should be changed to match the other.

[Triarii Triplus Contubernium (Plasma).blk.txt](https://github.com/MegaMek/megameklab/files/11184083/Triarii.Triplus.Contubernium.Plasma.blk.txt)

[Triarii Triplus Contubernium (Plasma).pdf](https://github.com/MegaMek/megameklab/files/11184058/Triarii.Triplus.Contubernium.Plasma.pdf)

**Comment by SJuliez** [comment] 2023-07-08 08:18
I cannot reproduce this at all, neither in 49.12 nor in the current version. Always prints a divisor of 2.

**Comment by neoancient** [comment] 2024-02-21 17:30
Closing due to inability to reproduce and no further information.

**Closed by neoancient** 2024-02-21 17:30 UTC
Labels: Can't reproduce
