### ISSUE TITLE
Uncaught java.lang.NullPointerException when closing mech selection window

### ISSUE THREAD

**Issue by FixDis** [MegaMek/megameklab#1369] opened 2024-01-03 04:40 UTC
### Environment
MegaMek v0.49.17 on Windows 11
Eclipse Adoptium Java Version: 11.0.21

### Description
Opening and closing the Load Existing Unit screen and Load Unit from Cache always causes the error message: Uncaught java.lang.NullPointerException

### Files
[megameklab.log](https://github.com/MegaMek/megameklab/files/13815715/megameklab.log)

**Comment by HammerGS** [comment] 2024-01-03 04:48
Fix pending. Duplicate of https://github.com/MegaMek/megameklab/issues/1370

**Closed by HammerGS** 2024-01-03 04:48 UTC
