### ISSUE TITLE
BA Flamers want a Fusion or Fission engine, causing Flamer BA to be invalid

### ISSUE THREAD

**Issue by KaiserFalk** [MegaMek/megameklab#1607] opened 2024-09-06 11:35 UTC
### Environment
Stand alone MekLab
Windows 10
Java 17

### Description
Flamer equipped Battle Armor squads are listed as invalid (F in level column) due to MekLab thinking their flamers require a fusion or fission engine. See below images. Seems to affect all Flamer BA

![image](https://github.com/user-attachments/assets/6a29ae2e-22cc-4ffc-a864-07a54aa723b7)

![image](https://github.com/user-attachments/assets/906d6afe-b57e-432f-ba4e-229cba61f811)

![image](https://github.com/user-attachments/assets/bf7c1163-ff68-4697-be44-2b65aafd45c7)

**Comment by pavelbraginskiy** [comment] 2024-09-06 13:00
Duplicate of MegaMek/megamek#5960

**Closed by pavelbraginskiy** 2024-09-06 13:00 UTC
