### ISSUE TITLE
Uncaught java.lang.NullPointerException

### ISSUE THREAD

**Issue by jimtheviking** [MegaMek/megameklab#1434] opened 2024-02-21 11:13 UTC
### Environment
Standalone 49.18 and MekHQ Lab 49.18
Win 11
Java 11.0.21

### Description
Whenever I try to add equipment to a Small Craft or Dropship, I get the following error: Uncaught java.lang.NullPointerException

This error persists across multiple re-downloads and unzips.

Log is attached.

[megameklab.log](https://github.com/MegaMek/megameklab/files/14358578/megameklab.log)

**Comment by HammerGS** [comment] 2024-02-21 15:23
Duplicate of https://github.com/MegaMek/megameklab/issues/1429

**Closed by HammerGS** 2024-02-21 15:23 UTC

**Comment by Sleet01** [comment] 2024-02-21 22:03
> Duplicate of #1429

Confirmed, and confirmed the MM-side fix has corrected this issue.
