### ISSUE TITLE
When exporting to PDF, ASF has 0 in Structural Integrity.

### ISSUE THREAD

**Issue by youROKer** [MegaMek/megameklab#1583] opened 2024-08-03 14:55 UTC
### Environment
0.49.20 dev. MHQ MML, same bug in 0.49.8 standalone MML
Windows
Java Version:  Oracle 17.0.1

### Description
When exporting to PDF, ASF has 0 in Structural Integrity, but this value is displayed correctly in MML itself. The same bug when exporting a unit to HTML file.

### Files
[pdf asf bug.zip](https://github.com/user-attachments/files/16480987/pdf.asf.bug.zip)

**Comment by pavelbraginskiy** [comment] 2024-08-10 06:51
Duplicate of #1474.
Workaround: Save and reload the unit.

**Closed by pavelbraginskiy** 2024-08-10 06:51 UTC
