### ISSUE TITLE
Fluff entries with line skips not saved

### ISSUE THREAD

**Issue by alexbib** [MegaMek/megameklab#847] opened 2020-12-18 23:41 UTC
Whenever I write a fluff entry (be it in capabilities, history, notes, etc.) that contains a line skip (just a normal return on the keyboard), everything after the line skip is lost when saving/loading.

Version 0.47.15 on Windows 10 64-bit.

**Comment by neoancient** [comment] 2020-12-19 02:28
Duplicate of Megamek/megamek#1757

**Closed by neoancient** 2020-12-19 02:28 UTC
Labels: duplicate
