### ISSUE TITLE
Incorrect Slot requirements for Anti-Personnel Gauss Rifles on Battle Armolr

### ISSUE THREAD

**Issue by Logion567** [MegaMek/megameklab#1209] opened 2022-12-25 01:27 UTC
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

MegaMek 0.49.10

Page 348 of Tech Manual has APGR listed as 2 slots as seen here 
![image](https://user-images.githubusercontent.com/98195429/209454584-ccd27ced-7d6a-465d-bac2-83509ffe4471.png)
**** while MML has it be 1 slot as seen here 
![image](https://user-images.githubusercontent.com/98195429/209454601-72dae1d4-9248-4339-8a2a-619532725550.png)

just a simple thing but can cause issues for custom unit building

**Comment by SJuliez** [comment] 2022-12-27 12:52
Duplicate of MM #4066.

**Closed by SJuliez** 2022-12-27 12:52 UTC
