### ISSUE TITLE
(0.49.7) Magnetic Clamps Missing From Equipment Database

### ISSUE THREAD

**Issue by wilkinswiki** [MegaMek/megameklab#1075] opened 2022-03-27 22:14 UTC
### Environment

MegaMekLab standalone
Windows 10
Java 11.0.11

### Description

Magnetic clamps are missing from the equipment database when designing battlearmor. Loading a unit that uses them will show them on the unit but not in the equipment selector.

### Files

![missing clamps](https://user-images.githubusercontent.com/67842850/160303176-ca8125b0-ffb5-440e-90c5-122336f61ea9.png)

**Comment by HammerGS** [comment] 2022-03-27 22:18
Duplicate of https://github.com/MegaMek/megameklab/issues/1062

**Closed** 2022-03-27 22:19 UTC
Labels: duplicate
