### ISSUE TITLE
[49.7] NPE when browsing Oni BattleArmor

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/megameklab#1072] opened 2022-03-21 19:57 UTC
megameklab.com.MegaMekLab.initializeLogging(MegaMekLab.java:97) - Starting MegaMekLab v0.49.7
	Release Date: 2022-02-18
	Today: 2022-03-21
	Origin Project: MegaMekLab
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.14
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_GB
	Total memory available to MegaMekLab: 1 GB

This NPE occurs when browsing the full unit list when choosing "Load Existing Unit". If you choose Oni Battle Armor, of the MMR or the PPC kind, the NPE happens.

I tested with version 48.0 and it shows me an empty entry (the NPE happens too, but it was silent at the time)

[megameklab.log](https://github.com/MegaMek/megameklab/files/8318857/megameklab.log)
[legacy.log](https://github.com/MegaMek/megameklab/files/8318858/legacy.log)
[megamek.log](https://github.com/MegaMek/megameklab/files/8318859/megamek.log)

**Comment by gsparks3** [comment] 2022-03-21 22:10
Technically a duplicate of [#3262](https://github.com/MegaMek/megamek/issues/3262), although given that issue got transferred to the Megamek repo I can see why you might have missed it. The logs with improved logging from 49.7 are probably useful, since the original issue report was from an older version.

**Comment by JonhyBurner** [comment] 2022-03-21 22:18
Good call. I only searched for exception and forgot to look for NPE. I'll leave it up to the devs whether they keep the new ticket or the old one.

**Comment by Windchild292** [comment] 2022-03-21 22:27
Duplicates https://github.com/MegaMek/megamek/issues/3262

Thanks for the find Mishra, and I'll note that this has better logs on the issue.

**Closed by Windchild292** 2022-03-21 22:27 UTC
