### ISSUE TITLE
MML doubling the cost of Machine Gun Arrays when multipe Arrays are in same location.

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megameklab#838] opened 2020-12-02 01:43 UTC
v.47.14

The Linebacker I (RecGuide 6), when built in MML, gives me a BV of 1929. Using SSW and hand calculating the BV returns 1853.

Testing in the MML shows that when multiple machine gun arrays are in the same location, the price of each array is being multiplied by the number of arrays in said location. So for example, when one 3-gun arrays is in a location, the BV cost for the array is 10.05--the correct value. If two 3-gun arrays are in a location, MML is charging 20.1 BV for each array (for a total of 40.2 for the two arrays). Etc.

Relevant BV rules are on page 317 of the TechManual.

**Comment by neoancient** [comment] 2020-12-02 02:17
Duplicate of MegaMek/megamek#2195

**Closed by neoancient** 2020-12-02 02:17 UTC
Labels: duplicate
