### ISSUE TITLE
0.45.4 problems with the export to clipboard (text) function

### ISSUE THREAD

**Issue by LiamsGhost** [MegaMek/megameklab#290] opened 2019-05-10 21:53 UTC
The export to clipboard function does not appear to work for dropships, or for mechs using patchwork armor. 

It acts as though something is exported, but when the paste command is used in a text editor, no information is pasted.

**Comment by neoancient** [comment] 2019-05-11 19:40
I could not reproduce the problem with mechs with patchwork armor. It may have been fixed by b3aa51.

**Closed** 2019-05-12 21:33 UTC
Labels: bug
