### ISSUE TITLE
Engine heatsink count gets screwed up when designing quadvees

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megameklab#73] opened 2017-08-30 09:23 UTC
When designing quadvees, the extra engine heatsinks sometimes still need to have their crits allocated.  The engine heatsink calculation seems to work okay until I select the "Omni" checkbox.

**Comment by BLR-IIC** [comment] 2017-08-30 09:27
Played with this more and realized that the functionality of adding heat sinks appears to have somewhat changed since I last used MML, particularly when designing omnis.  I don't believe there is a problem here.

**Comment by neoancient** [comment] 2017-09-16 18:10
When building an OmniMech you must designate how many of the heat sinks are part of the base chassis design. Any that are not part of the base chassis must be allocated critical space, even if they would be part of the engine in a non-omni. You can't pod-mount integral heat sinks. If this is not what is happening, please describe the steps needed to reproduce, your results, and how they differ from what you expect.

**Comment by neoancient** [comment] 2017-10-02 18:00
Closing due to lack of any indication of a problem.

**Closed by neoancient** 2017-10-02 18:00 UTC
