### ISSUE TITLE
"Uncaught exception detected" prompt when loading official file

### ISSUE THREAD

**Issue by HuntingTarg** [MegaMek/megameklab#1214] opened 2023-01-01 22:45 UTC
MegaMekLab prompt upon loading program file: 
>Java.Lang.ExceptionOutOfBoundsException detected.

### Environment
MekLab 49.10
Windows 10 (current as of 1/1/23)
Eclipse Temurin JDK 11.0.17.8

### Description
Loading 'existing file' from MegaMekLab splash screen (file included).  On selecting from load interface window, file loads displaying error message and prompting issue creation.  Did not find any similar among open issues in MML Repository.  Screenshot included.  Could not reproduce error dialog box.

### Files
Screenshot and logfile attached.  GitHub did not allow attachment of original unit record file (Aerospace fighter Slayer variant SL-15K ).
![MML_Error_Screenshot_01](https://user-images.githubusercontent.com/53635722/210186522-d1ca013b-c9de-4396-bf6a-7c39697e0238.jpg)
[megameklab.log](https://github.com/MegaMek/megameklab/files/10329576/megameklab.log)

**Comment by HammerGS** [comment] 2023-01-01 22:49
You should be able to zip the unit file which would be a help.

**Comment by HammerGS** [comment] 2023-01-01 22:49
```
13:37:00,389 ERROR [megameklab.MegaMekLab] {AWT-EventQueue-0}
megameklab.MegaMekLab.lambda$main$0(MegaMekLab.java:39) - Uncaught Exception Detected
java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 4
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at java.desktop/javax.swing.JTabbedPane.isEnabledAt(JTabbedPane.java:1219)
	at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI.getIconForTab(BasicTabbedPaneUI.java:1942)
	at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI.calculateTabHeight(BasicTabbedPaneUI.java:1985)
	at com.formdev.flatlaf.ui.FlatTabbedPaneUI.calculateTabHeight(FlatTabbedPaneUI.java:847)
	at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI.calculateMaxTabHeight(BasicTabbedPaneUI.java:2007)
	at com.formdev.flatlaf.ui.FlatTabbedPaneUI.calculateMaxTabHeight(FlatTabbedPaneUI.java:859)
	at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI$TabbedPaneLayout.calculateTabRects(BasicTabbedPaneUI.java:3001)
	at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI$TabbedPaneLayout.calculateLayoutInfo(BasicTabbedPaneUI.java:2922)
	at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI$TabbedPaneLayout.layoutContainer(BasicTabbedPaneUI.java:2814)
	at com.formdev.flatlaf.ui.FlatTabbedPaneUI$FlatTabbedPaneLayout.layoutContainer(FlatTabbedPaneUI.java:2816)
	at java.desktop/java.awt.Container.layout(Container.java:1537)
	at java.desktop/java.awt.Container.doLayout(Container.java:1526)
	at java.desktop/java.awt.Container.validateTree(Container.java:1722)
	at java.desktop/java.awt.Container.validate(Container.java:1657)
	at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI.ensureCurrentLayout(BasicTabbedPaneUI.java:1646)
	at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI.tabForCoordinate(BasicTabbedPaneUI.java:1687)
	at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI.tabForCoordinate(BasicTabbedPaneUI.java:1681)
	at com.formdev.flatlaf.ui.FlatTabbedPaneUI.tabForCoordinate(FlatTabbedPaneUI.java:1447)
	at com.formdev.flatlaf.ui.FlatTabbedPaneUI$Handler.updateRollover(FlatTabbedPaneUI.java:2549)
	at com.formdev.flatlaf.ui.FlatTabbedPaneUI$Handler.mouseEntered(FlatTabbedPaneUI.java:2522)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6644)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEnterExit(Container.java:4698)
	at java.desktop/java.awt.LightweightDispatcher.trackMouseEnterExit(Container.java:4676)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4527)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by HuntingTarg** [comment] 2023-01-01 22:52
Done.  File was pulled from a compressed directory, so it might be 'double-zipped.'
[Slayer SL-15K.zip](https://github.com/MegaMek/megameklab/files/10329593/Slayer.SL-15K.zip)

**Comment by HuntingTarg** [comment] 2023-01-01 22:58
Something congruent ocurred once before, but that was a more complex situation: I was trying to create a variant by using an existing file and changing specs without removing specific equipment not available on the Equipment List for the desired era (or, as far as I understand MML and source material, any era:  Chameleon Light Polarization Shield and Null Signature System).  Screenshot attached.  The file loaded was Battlemech File Exterminator EXT-4C (Offical unit file and screenshot attached.)
![MML_Error_Screenshot_1](https://user-images.githubusercontent.com/53635722/210186860-7c9ea9f8-9981-43da-a875-dcf60a78d0e7.jpg)
[Exterminator EXT-4C.zip](https://github.com/MegaMek/megameklab/files/10329606/Exterminator.EXT-4C.zip)

**Comment by SJuliez** [comment] 2023-01-19 17:51
I can't reproduce this. Loading a Slayer 15K does not result in an error.

**Comment by SJuliez** [comment] 2023-07-08 08:22
I'm hoping that these loading errors were threading-related in which case the cause has been removed. Closing this, asking anyone to re-open if this occurs again with current versions of MML.

**Closed by SJuliez** 2023-07-08 08:22 UTC
Labels: Bug, Can't reproduce
