### ISSUE TITLE
PPC Capacitor not latching onto PPCs in Combat Vehicles

### ISSUE THREAD

**Issue by GamerFoxNeumann** [MegaMek/megameklab#417] opened 2020-02-03 04:38 UTC
I've been playing with 0.47.3 MegaMekLab vehicle designer and I've started to encounter a problem, a problem where when loading a combat vehicle with a PPC and a PPC capacitor: the designer states that it won't load the vehicle due to the capacitor not being matted to a PPC.

Is this a reoccurring problem or is it just me?

**Comment by neoancient** [comment] 2020-02-07 16:15
Among the provided combat vehicles, the following have PPC capacitors:
Goblin Medium Tank X
Nemara Armored Fighting Vehicle Mk XI-FC
Schrek II-X PPC Carrier (Standard)
Zephyr Hovertank (Omnidrone) Prime

All load without error. Please provide the file for the design that is failing.

**Comment by GamerFoxNeumann** [comment] 2020-02-07 17:45
> Among the provided combat vehicles, the following have PPC capacitors:
> Goblin Medium Tank X
> Nemara Armored Fighting Vehicle Mk XI-FC
> Schrek II-X PPC Carrier (Standard)
> Zephyr Hovertank (Omnidrone) Prime
> 
> All load without error. Please provide the file for the design that is failing.

First, they got deleted when I kept getting stonewalled... and the odd thing is that it is allowing me to get 'prebuilt' ones. I'll have to make a design that causes the problem again.

**Comment by HammerGS** [comment] 2020-02-08 15:32
When you have that design please post it here.

**Comment by neoancient** [comment] 2020-02-18 18:13
I tried creating a new combat vehicle with a PPC and capacitor and still couldn't reproduce. Closing due to lack of evidence.

**Closed by neoancient** 2020-02-18 18:13 UTC
Labels: Can't reproduce
