### ISSUE TITLE
Unable to initialize main class megameklab.MegaMekLab (suite preferences module)

### ISSUE THREAD

**Issue by me0262** [MegaMek/megameklab#1218] opened 2023-01-05 22:30 UTC
Megameklab does not run when launched from cli.
Looks like it's related to the entire suite, which I only run the lab.

### Environment
What version of MekLab does your issue apply to?  Note whether it is the stand alone MekLab or HQ's MekLab.
What operating system are you using?  Mac OS 10.15
What java version are you using?
```
MacBook-Pro:megameklab-0.49.11 me262$ java --version
java 11.0.8 2020-07-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.8+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode)
```

### Description
```
MacBook-Pro:megameklab-0.49.11 me262$ ./mml-startup 
Error: Unable to initialize main class megameklab.MegaMekLab
Caused by: java.lang.NoClassDefFoundError: megamek/client/ui/preferences/SuitePreferences
```

### Files
No log file generated

**Comment by HammerGS** [comment] 2023-01-05 22:37
Not the Mac expert but have a look here - https://megamek.org/wiki/mac_issues.html

**Comment by rjhancock** [comment] 2023-01-05 22:39
What folder are you launching from?

**Comment by rjhancock** [comment] 2023-01-05 22:46
```
 ~/Games/mekhq-0.49.11/ java --version
openjdk 11.0.17 2022-10-18
OpenJDK Runtime Environment Homebrew (build 11.0.17+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.17+0, mixed mode)
```

and it loads fine using `java -jar <jarfile>`

**Comment by me0262** [comment] 2023-01-05 22:46
Launching directly in the folder.
/Users/me262/Applications/megameklab-0.49.11/

**Comment by me0262** [comment] 2023-01-05 22:49
> and it loads fine using `java -jar <jarfile>`
Same output for me, unable to initialize main class.

**Comment by rjhancock** [comment] 2023-01-05 22:55
I'd suggest you remove the installer version and use the instructions pointed to by @HammerGS on the main site. So long as they are followed, things should work fine.

**Comment by me0262** [comment] 2023-01-05 22:57
Please read edited comment, I have 0.49.7 on here and it works fine. Not sure if that complicates things.

**Comment by rjhancock** [comment] 2023-01-05 22:59
I did read the edited comment before I commented. Please remove the installer version you have and use the instructions posted above on the main site.

**Comment by me0262** [comment] 2023-01-05 23:07
I will try Oracle Java 17 first, I've had a very bad experience with Homebrew.

**Comment by me0262** [comment] 2023-01-05 23:10
Same result.
```
MacBook-Pro:megameklab-0.49.11 me262$ java --version
java 17.0.5 2022-10-18 LTS
Java(TM) SE Runtime Environment (build 17.0.5+9-LTS-191)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.5+9-LTS-191, mixed mode, sharing)
MacBook-Pro:megameklab-0.49.11 me262$ ./mml-startup 
Error: Unable to initialize main class megameklab.MegaMekLab
Caused by: java.lang.NoClassDefFoundError: megamek/client/ui/preferences/SuitePreferences
```

**Comment by rjhancock** [comment] 2023-01-06 01:51
I've tried this several different ways using the OpenJDK@11 Brew package linked to the system virtual machines with no other version of Java installed and it is working from the shell script, command line, AND double clicking of the JAR file.

This is a local issue for your machine. Please check the `JavaVirtualMachine` folder for more than one Java instance. More than likely, this is caused by multiple java VMs being on the machine and the MML Setup script is grabbing the wrong one or the system is using the wrong one when trying to run via the `-jar` command.

**Comment by me0262** [comment] 2023-01-06 13:15
Removed all other java VMs apart from Oracle 17, same issue. 0.49.7 continues to work.
I redownloaded megameklab-0.49.11 and extracted, same result.
I downloaded the full suite (meklab-0.49.11), and megameklab within that suite works.

**Comment by rjhancock** [comment] 2023-01-06 14:32
For the last time, please follow the instructions provided on the main site. They are confirmed working. Unable to duplicate your issue on any of my Mac's (4 of them). This is a local issue to your machine.

@HammerGS Please close this ticket as unreproducible.

**Comment by HammerGS** [comment] 2023-01-06 15:38
> Removed all other java VMs apart from Oracle 17, same issue. 0.49.7 continues to work. I redownloaded megameklab-0.49.11 and extracted, same result. I downloaded the full suite (mekhq-0.49.11), and megameklab within that suite works.

I want to confirm something. 

If you use the MegaMekLab **ONLY** release it won't run. But if you download the MekHQ release (with all three programs) it does run?

**Comment by me0262** [comment] 2023-01-06 15:48
> If you use the MegaMekLab **ONLY** release it won't run. But if you download the MekHQ release (with all three programs) it does run?

Correct.

**Comment by HammerGS** [comment] 2023-01-06 16:49
> > If you use the MegaMekLab **ONLY** release it won't run. But if you download the MekHQ release (with all three programs) it does run?
> 
> Correct.
> 
> EDIT: I also confirmed on my Linux system that megameklab standalone also fails to startup with the same error. That's running OpenJDK 17.0.3. megameklab as part of the mekhq bundle does start up on that same setup.

We've identified this is an issue in the standalone releases. You'll need to use the MekHQ bundle to get MML to work.

**Closed** 2023-01-09 01:41 UTC
Labels: Blocker, Build / CI
