### ISSUE TITLE
Primitive 'Mech Cockpit Weight Incorrect 0.47.2

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megameklab#400] opened 2020-01-20 00:51 UTC
When building a new unit, I selected the option to make a primitive 'mech.  However, the weight of the primitive 'mech cockpit is still 3 tons and not 5 tons.

**Comment by neoancient** [comment] 2020-01-20 15:58
Where are you seeing 3 tons?

![Screenshot from 2020-01-20 09-55-15](https://user-images.githubusercontent.com/16927464/72740491-62011900-3b6b-11ea-8c04-37f4adc0be67.png)
![Screenshot from 2020-01-20 09-55-37](https://user-images.githubusercontent.com/16927464/72740500-6594a000-3b6b-11ea-9398-df379d6c1cd1.png)

**Comment by neoancient** [comment] 2020-01-20 18:36
So the problem is not cockpit weight. The problem is that it doesn't actually switch to primitive. I had forgotten about that bug. It was fixed by #377.

**Closed by neoancient** 2020-01-20 18:36 UTC
