### ISSUE TITLE
MML: Quad mech turret faction availability incorrect

### ISSUE THREAD

**Issue by avincentelli** [MegaMek/megameklab#628] opened 2020-05-19 20:36 UTC
### Environment
MegaMekLab via mekhq-windows-0.46.1
Java Version 8 Update 251 (build 1.8.0_251-b08)

### Description
Currently in MML, the Experimental equipment "BattleMech Turret (Quad)" is listed as only being available for an Inner Sphere tech base. However, per Tactical Operations pages 347 (which is referenced in MML) and 411, and per Interstellar Operations page 50, Quad mech turrets should be available to both IS and Clan factions.

### Files
[picture_guide.zip](https://github.com/MegaMek/megameklab/files/4652980/picture_guide.zip)

**Comment by neoancient** [comment] 2020-05-20 15:43
Duplicate of MegaMek/megamek#1755, fixed in MegaMek/megamek@0380271

**Closed by neoancient** 2020-05-20 15:43 UTC
Labels: duplicate
