### ISSUE TITLE
[RULES] IndustrialMechs *should* be able to mount Torso Cockpits

### ISSUE THREAD

**Issue by NimoStar** [MegaMek/megameklab#794] opened 2020-10-06 14:33 UTC
The Torso Cockpit is explicitely listed in rules as being available for BattleMechs and IndustrialMechs alike.

Yet in MegaMekLab, inexplainably, only BattleMechs can mount it

### Environment
47.10

### Description
Strategic Operations, Page 301
![2020-10-06 11_29_10-Tactical Operations - CAT35003TacticalOperations pdf](https://user-images.githubusercontent.com/38392980/95215629-8d926500-07c7-11eb-90e3-c61922aa3078.png)
In MegaMekLab
![2020-10-06 11_32_02-Ronald RNLD-SP1 mtf](https://user-images.githubusercontent.com/38392980/95215705-a864d980-07c7-11eb-9b95-9c83d6f1bc33.png)

**Comment by neoancient** [comment] 2020-10-06 14:35
Duplicate of #638

**Closed by neoancient** 2020-10-06 14:35 UTC
Labels: duplicate
