### ISSUE TITLE
BA Support and APM weapons not loading correctly

### ISSUE THREAD

**Issue by lenny53207** [MegaMek/megameklab#688] opened 2020-07-21 23:08 UTC
### Environment
What version of MekLab does your issue apply to? mekhq-windows-0.46.1
What operating system are you using? Windows
What java version are you using? Version 8 Update 251

### Description
I have an assault BA design with 2 AP weapons in AP mounts on the body and a support weapon in the hands.  The design validates and saves fine in megameklab.  When I reload the design in megameklab or try to load in megamek it says it is invalid and lists the AP weapons mounted in the hands and no room for the support weapon.

### Files

[ABA Shredder.zip](https://github.com/MegaMek/megameklab/files/4956897/ABA.Shredder.zip)

**Comment by neoancient** [comment] 2020-07-22 01:57
This was fixed by MegaMek/megamek#1691. It is working in the development releases and will be in the next stable release, which currently has no ETA.

**Comment by neoancient** [comment] 2020-07-22 01:58
Duplicate of #441

**Closed by neoancient** 2020-07-22 01:57 UTC
Labels: Outdated
