### ISSUE TITLE
1.53 : MML allows you to use invalid ammo

### ISSUE THREAD

**Issue by Question2** [MegaMek/megameklab#13] opened 2016-05-19 05:30 UTC
For example if you are makig a mixtech unit, you can set it to use IS Tandem charge SRM ammo with clan SRM launchers. Megamek won't allow this however and will force the unit to use normal SRM ammo (although it still uses the half ammo per ton penalty of TC ammo).

MML shouldnt be displaying invalid ammo options if megamek won't allow it.

[megameklablog.txt](https://github.com/MegaMek/megameklab/files/271895/megameklablog.txt)

**Comment by BLOODWOLF333** [comment] 2016-07-17 15:17
Well, do you have "allow invalid designs" option checked in Megamek with unofficial tech level to see if it will accept it?

**Comment by Dylan-M** [comment] 2016-10-05 10:31
The question is: By the rules should we be allowing ammo cross-overs?

If so, then this is a bug with MM rather than MML.

**Comment by pheonixstorm** [comment] 2016-10-06 00:43
I think IO covers this question, or perhaps it was a thread on the official forums. I will have a look and post a reference if I can find it. I know its out there...

**Comment by Question2** [comment] 2016-12-27 16:13
The issue is more that MM can spot that it is a invalid unit because tandem charge ammo is IS only (Tacops page 372, techbase is IS only) while MML cannot and the unit validation check is passing it (just tested again in 41.28).

**Comment by Dylan-M** [comment] 2016-12-27 16:19
Actually, MML's unit validation is actually MM's unit validation (we use MM as a library for MML to do things like this in 1 consistent place), so it will pass validation regardless.

This means the issue is there, and it turning it into "regular" SRM ammo is just an artifact of the real bug.

However, mixed tech designs present an additional challenge, because if you have a mixed tech design that has an IS SRM launcher, it should be able to use the Tandem ammo. This means we have to validate at the equipment level. This shouldn't be terribly difficult, just... annoying. It also means we would have to handle special cases in MM where you have both Clan and IS launchers on the same chassis. We would need to not include the invalid ammo types on the lists for the other launchers, which is very much the way it works now for all weapons.

**Comment by neoancient** [comment] 2017-02-18 18:02
http://bg.battletech.com/forums/index.php?topic=47832.0
Clan launchers can fire IS ammo and vice-versa, but the example in this rules clarification (that minimum range applies when using IS ammo with a Clan LRM launcher) presents additional problems for support in MM. As it stands MML allows a legal build, but MM does not necessarily support it.

**Comment by neoancient** [comment] 2019-03-21 13:00
Coming back to this after a long time it is apparent to me that I already made the case that this is not a bug in MML. The fact that MML allows you to build something that doesn't work in MM is not a problem either, since MML isn't necessarily limited to producing units for use in MM.

**Closed by neoancient** 2019-03-21 13:00 UTC
Labels: bug
