### ISSUE TITLE
Warships all have Tele Operated Missiles

### ISSUE THREAD

**Issue by 2ndacr** [MegaMek/megameklab#387] opened 2019-12-21 19:04 UTC
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
What version of MekLab does your issue apply to?  0.47.2 MekHQ
What operating system are you using?  Windows 10
What java version are you using?  If unsure it will state your java version at the top of the megameklablog.txt file.
(Delete the above lines)

### Description
 When loading or viewing warships they all have Tele Operated Missiles regardless of time frame. 

### Files
Provide the megameklablog.txt file for any NPE's or errors that MekLab might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual megameklablog.txt file
And provide the unit's file that the issue relates to if this is a unit-specific bug.
(Delete the above lines)

**Comment by HammerGS** [comment] 2019-12-21 19:12
Duplicate of https://github.com/MegaMek/megameklab/issues/373

Fixed

**Closed by HammerGS** 2019-12-21 19:12 UTC
Labels: duplicate
