### ISSUE TITLE
Multi-location weapons on superheavy mechs

### ISSUE THREAD

**Issue by Xeno426** [MegaMek/megameklab#68] opened 2017-08-08 22:13 UTC
I've run into an odd problem with superheavy mechs. Normally, each crit space on the mech can accommodate two weapon crits, which allow large weapons like AC/20s to double up on one location (i.e. two AC/20s in the arm. In particular, some of these weapons (like the LB-20X) can be added to the center torso thanks to the reduce space the engine takes up. For illustrative purposes, I'll be using the AC/20.

I've run into the problem where the program doesn't seem to understand that it's possible to have five AC/20s, one in each arm and torso. Placing an AC/20 into the CT prompts the secondary location box. After saving, however, the program splits the AC/20 in the torsos into the adjacent arms, effectively removing two weapons. 

This is easily replicated for any superheavy mech carrying the same multi-location capable weapon in a adjacent locations (an AC/20 in LA and LT, an LB-20X in the RT and CT, etc). Simply save the mech and load it back up.

**Comment by HammerGS** [comment] 2017-08-09 01:28
Duplicate of https://github.com/MegaMek/megamek/issues/588

**Comment by neoancient** [comment] 2017-08-09 01:29
Except this one is at least on the correct tracker.

**Comment by neoancient** [comment] 2017-08-09 02:53
Hammer was correct. This was an issue with the way the unit file is loaded. Fixed in MegaMek/megamek@88a6b61

**Closed by neoancient** 2017-08-09 02:53 UTC
Labels: duplicate
