### ISSUE TITLE
(0.45.1) Large amounts of weapons overtax warship creation

### ISSUE THREAD

**Issue by UB-JM** [MegaMek/megameklab#237] opened 2018-12-20 00:38 UTC
### Environment
0.45.1
Java 8
Windows 10

### Description
Using very large amounts of weapons, f.Ex. small arms, on warship designs periodically confuses the software.
F.Ex. a bay of 200 machine guns might suddenly be 200 singular guns, with the ammo somehow still allocated in the correct arc even though there's no bay left. 
Even if that doesn't happen, with large amounts of weapons MML insists that the left and right side do not match when checking for validity. 
Checking for that, clan MGs also have 2 different ammo items.

### Files
The log seems completely unaware of any problems. I might try to catch a different file later.

![capture2](https://user-images.githubusercontent.com/19310656/50274667-134fef80-043e-11e9-8e18-b9d40e3be0bc.PNG)
![capture3](https://user-images.githubusercontent.com/19310656/50274882-65911080-043e-11e9-8507-f5a8d5f875b4.PNG)
I didn't manage to reproduce the "bay suddenly disintegrating" issue today for a picture, I'll try again later.

**Comment by HammerGS** [comment] 2018-12-20 01:06
The left/right is a duplicate of https://github.com/MegaMek/megameklab/issues/234, and should be fixed for the next release.

**Comment by UB-JM** [comment] 2018-12-20 09:51
Ah, ok, I thought as I didn't even have a general hull section that could have been different. 
I'll try to get a picture and or log of the main issue later, takes forever to juggle that many items.

**Comment by neoancient** [comment] 2019-01-30 15:32
That pointed me in the right direction. The Point Defense Bay never had a bad intro year that was generated from the tech level data by the conversion process when the IO tech advancement dates were added. So when the year is changed to anything earlier than the tech level sample date of 3071, the point defense bay is removed because MML's data says it wasn't invented yet. I double-checked the rest of the bays and this was the only one affected.

**Closed** 2019-01-30 16:34 UTC
