### ISSUE TITLE
47.9 Formatting error for quarters and seating on support vehicle record sheets

### ISSUE THREAD

**Issue by LiamsGhost** [MegaMek/megameklab#757] opened 2020-08-29 23:39 UTC
All quarters/seating on all support vehicles record sheets add tons to their listed quantities. For example, a large support vehicle carrying seven steerage quarters and one second class quarters will be listed on the record sheet as Steerage Quarters (7 tons) and Second Class Quarters (1 ton) rather than (7) and (1) respectively. The same applies for standard or pillion seats on support vehicles of either size category.

**Comment by neoancient** [comment] 2020-08-29 23:52
Duplicate of #726

**Closed by neoancient** 2020-08-29 23:52 UTC
Labels: duplicate
