### ISSUE TITLE
Queued Printing not printing all units in list

### ISSUE THREAD

**Issue by olaughlj** [MegaMek/megameklab#175] opened 2018-07-31 17:42 UTC
MegaMekLabs 0.44.0
Windows 10
Java 1.8.0 181

When attempting to print out a large number of mech sheets (20+) for an upcoming tournament using the Unit Print Queue dialog, after adding units to the list I would press the print button and proceed with printing. I was usually only seeing the first 16 or so actually print out.

[megameklablog.txt](https://github.com/MegaMek/megameklab/files/2246474/megameklablog.txt)

**Comment by wildj79** [comment] 2018-07-31 17:47
Could you provide a list of units you were trying to print? Also, were there any custom units? If so, could you provide the MTF's for those as well.

**Comment by olaughlj** [comment] 2018-07-31 17:50
All cached units, below is the total list of units I was attempting to print. First print attempt got into the Thors (I believe through the Thor C), then I proceeded to enter the rest of the list and got everything but the Thor II and Vulture III.

Matador
Thresher
Cauldron Born A
Cauldron Born D
Linebacker Prime
Linebacker A
Linebacker B
Loki Prime
Loki F
Grizzly
Guillotine IIC
Nova Cat C
Thor Prime
Thor A
Thor C
Thor F
Thor H
Thor M
Mad Cat Prime
Mad Cat B
Mad Cat C
Mad Cat H
Mad Cat S
Phoenix Hawk IIC 3
Warhammer IIC 3
Omen
Deimos Prime
Highlander IIC
Kingfisher A
Kingfisher B
Thor II Prime
Vulture Mk III B

**Comment by neoancient** [comment] 2018-08-08 21:35
I tried testing this by printing this list to a PDF and had no problem. Here are some steps that could help narrow it down:
1. Are you using fluff images for any of the units?
2. Does it finish the print job if you print to a file?
3. If it does print the complete job to a file, can you then print that on the printer?

**Comment by neoancient** [comment] 2019-03-21 19:07
Closing due to inability to reproduce and no further information provided.

**Closed by neoancient** 2019-03-21 19:07 UTC

**Comment by popnfloss** [comment] 2019-08-26 12:28
I'm having this problem as well. I queue a bunch of units to print to PDF with fluff images and after about 45 or so units, MML eats up tons of memory and seems to just give up. The print job completes but the PDF is unfinished.
