### ISSUE TITLE
Heavy Gauss Rifle error

### ISSUE THREAD

**Issue by cdalmas** [MegaMek/megameklab#349] opened 2019-10-04 19:13 UTC
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment

What version of MekLab does your issue apply to?  Note whether it is the stand alone MekLab or 
Windows 7, Windows 10
Standalone
(Delete the above lines)

### Description

Allows HGRs to be installed in the arms.
(Delete the above lines)

**Comment by HammerGS** [comment] 2019-10-04 19:15
Duplicate of #324 and fixed.

**Closed by HammerGS** 2019-10-04 19:15 UTC
Labels: duplicate

**Comment by cdalmas** [comment] 2019-10-04 19:19
I installed my copy of MegaMek a month ago. It's not fixed. Was this fix
done within the last month?

C.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Am Fr., 4. Okt. 2019 um 15:15 Uhr schrieb Dave N <notifications@github.com>:

**Comment by HammerGS** [comment] 2019-10-04 19:21
It will be in the next Dev release.

**Comment by cdalmas** [comment] 2019-10-04 19:23
Got you. Thanks! Have a great weekend.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Am Fr., 4. Okt. 2019 um 15:21 Uhr schrieb Dave N <notifications@github.com>:
