### ISSUE TITLE
Crit-Splitting, Structural Components, and OmniMechs

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megameklab#1089] opened 2022-04-17 03:01 UTC
v.49.8 Nightly

This bug is purely related to the new nightly build.

I'm coming across an interesting interaction when attempting to split larger weapons between locations on OmniMechs. I'm having trouble pinning down the exact requirements for this interaction to happen, but I believe a unit being an Omni might play a part.

When dropping the weapon into an arm, specifically onto an actuator or a structural crit, one of the following happens. In example one, the HAG disappears from the arm and only a single crit appears in the torso. In example two, the HAG replaces one of the endo slots, but doesn't appear elsewhere.

![Capture](https://user-images.githubusercontent.com/17106678/163698379-c519dc64-a9f9-4553-a680-2e6c9dac4ac2.PNG)
![Capture 2](https://user-images.githubusercontent.com/17106678/163698381-f88c2f76-42b5-45ae-8144-2a322638a88f.PNG)

**Comment by neoancient** [comment] 2024-01-24 01:54
Can't reproduce. Closing due to age and likelihood that the code has changed.

**Closed by neoancient** 2024-01-24 01:54 UTC
Labels: Bug, Mek
