### ISSUE TITLE
47.9 Harjel in head

### ISSUE THREAD

**Issue by Diplominator** [MegaMek/megameklab#751] opened 2020-08-18 19:17 UTC
In MML 47.9, I get a popup saying I cannot put Harjel in the head when I try to put Harjel II or III in the head of a Superheavy 'Mech or a 'Mech with a small cockpit.

While I can find reference to banning this for the original Battlemech Harjel system in Tacops, as far as I can tell there is no such restriction on Harjel II or III in FM 3145 or IntOps. I even checked the IntOps errata.

**Comment by neoancient** [comment] 2020-08-18 20:30
Duplicate of MegaMek/megamek#2161

**Closed by neoancient** 2020-08-18 20:30 UTC
Labels: duplicate
