### ISSUE TITLE
v 49.6 Cost Calculation Errors

### ISSUE THREAD

**Issue by LilyFromSangvisFerri** [MegaMek/megameklab#1051] opened 2022-02-27 06:23 UTC
MekLab from the bundle download v 49.6 is yielding a BV Calculation Window instead of Cost Calculation Windows when Unit Cost Breakdown is opened. The unit types affected are: Infantry, BattleArmor, Aerospace Fighters, Primitive Aerospace Fighters, Conventional Fighters, and Primitive Conventional Fighters. This applies to all units of the affected types.

OS is Windows 10, Java Version is 11.0.11.

Steps to reproduce: Open a unit of any of the affected unit types, and select any option in Unit Cost Breakdown under Unit Validation. (If needed, select one of the affected unit types again.)

[megameklablog.txt](https://github.com/MegaMek/megameklab/files/8148154/megameklablog.txt)

**Comment by HammerGS** [comment] 2022-02-27 15:40
Duplicate of https://github.com/MegaMek/megameklab/issues/494

**Closed by HammerGS** 2022-02-27 15:40 UTC
Labels: duplicate
